package run;
// Generated Jun 11, 2021, 1:48:56 AM by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Articles generated by hbm2java
 */
public class Articles implements java.io.Serializable {

	private Integer idArticle;
	private String articleName;
	private String description;
	private double price;
	private int stock;
	private Set shoppingCarts = new HashSet(0);

	public Articles() {
	}

	public Articles(String articleName, String description, double price, int stock) {
		this.articleName = articleName;
		this.description = description;
		this.price = price;
		this.stock = stock;
	}

	public Articles(String articleName, String description, double price, int stock, Set shoppingCarts) {
		this.articleName = articleName;
		this.description = description;
		this.price = price;
		this.stock = stock;
		this.shoppingCarts = shoppingCarts;
	}

	public Integer getIdArticle() {
		return this.idArticle;
	}

	public void setIdArticle(Integer idArticle) {
		this.idArticle = idArticle;
	}

	public String getArticleName() {
		return this.articleName;
	}

	public void setArticleName(String articleName) {
		this.articleName = articleName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	public Set getShoppingCarts() {
		return this.shoppingCarts;
	}

	public void setShoppingCarts(Set shoppingCarts) {
		this.shoppingCarts = shoppingCarts;
	}

}
