package run;
// Generated Jun 11, 2021, 1:48:56 AM by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * Billing generated by hbm2java
 */
public class Billing implements java.io.Serializable {

	private Integer idBilling;
	private PurchaseOrders purchaseOrders;
	private int idNumber;
	private double amount;
	private Date date;

	public Billing() {
	}

	public Billing(PurchaseOrders purchaseOrders, int idNumber, double amount, Date date) {
		this.purchaseOrders = purchaseOrders;
		this.idNumber = idNumber;
		this.amount = amount;
		this.date = date;
	}

	public Integer getIdBilling() {
		return this.idBilling;
	}

	public void setIdBilling(Integer idBilling) {
		this.idBilling = idBilling;
	}

	public PurchaseOrders getPurchaseOrders() {
		return this.purchaseOrders;
	}

	public void setPurchaseOrders(PurchaseOrders purchaseOrders) {
		this.purchaseOrders = purchaseOrders;
	}

	public int getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(int idNumber) {
		this.idNumber = idNumber;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
