package run;
// Generated Jun 11, 2021, 1:48:56 AM by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer idCity;
	private Country country;
	private States states;
	private String city;
	private int postalCode;
	private Set deliveryAdresses = new HashSet(0);

	public City() {
	}

	public City(Country country, States states, String city, int postalCode) {
		this.country = country;
		this.states = states;
		this.city = city;
		this.postalCode = postalCode;
	}

	public City(Country country, States states, String city, int postalCode, Set deliveryAdresses) {
		this.country = country;
		this.states = states;
		this.city = city;
		this.postalCode = postalCode;
		this.deliveryAdresses = deliveryAdresses;
	}

	public Integer getIdCity() {
		return this.idCity;
	}

	public void setIdCity(Integer idCity) {
		this.idCity = idCity;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public States getStates() {
		return this.states;
	}

	public void setStates(States states) {
		this.states = states;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

	public Set getDeliveryAdresses() {
		return this.deliveryAdresses;
	}

	public void setDeliveryAdresses(Set deliveryAdresses) {
		this.deliveryAdresses = deliveryAdresses;
	}

}
