package run;
// Generated Jun 11, 2021, 1:48:56 AM by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

	private Integer idCountry;
	private String country;
	private Set cities = new HashSet(0);
	private Set deliveryAdresses = new HashSet(0);
	private Set stateses = new HashSet(0);

	public Country() {
	}

	public Country(String country) {
		this.country = country;
	}

	public Country(String country, Set cities, Set deliveryAdresses, Set stateses) {
		this.country = country;
		this.cities = cities;
		this.deliveryAdresses = deliveryAdresses;
		this.stateses = stateses;
	}

	public Integer getIdCountry() {
		return this.idCountry;
	}

	public void setIdCountry(Integer idCountry) {
		this.idCountry = idCountry;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set getCities() {
		return this.cities;
	}

	public void setCities(Set cities) {
		this.cities = cities;
	}

	public Set getDeliveryAdresses() {
		return this.deliveryAdresses;
	}

	public void setDeliveryAdresses(Set deliveryAdresses) {
		this.deliveryAdresses = deliveryAdresses;
	}

	public Set getStateses() {
		return this.stateses;
	}

	public void setStateses(Set stateses) {
		this.stateses = stateses;
	}

}
