package run;
// Generated Jun 11, 2021, 1:48:56 AM by Hibernate Tools 5.4.30.Final

/**
 * CreditCards generated by hbm2java
 */
public class CreditCards implements java.io.Serializable {

	private Integer idCreditCard;
	private Clients clients;
	private InformationCc informationCc;

	public CreditCards() {
	}

	public CreditCards(Clients clients, InformationCc informationCc) {
		this.clients = clients;
		this.informationCc = informationCc;
	}

	public Integer getIdCreditCard() {
		return this.idCreditCard;
	}

	public void setIdCreditCard(Integer idCreditCard) {
		this.idCreditCard = idCreditCard;
	}

	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	public InformationCc getInformationCc() {
		return this.informationCc;
	}

	public void setInformationCc(InformationCc informationCc) {
		this.informationCc = informationCc;
	}

}
