package run;
// Generated Jun 11, 2021, 1:48:56 AM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PurchaseOrders generated by hbm2java
 */
public class PurchaseOrders implements java.io.Serializable {

	private Integer idPurchaseOrder;
	private DeliveryAdress deliveryAdress;
	private Date purchaseDate;
	private DeliveryPackages deliveryPackages;
	private Billing billing;
	private Set shoppingCarts = new HashSet(0);

	public PurchaseOrders() {
	}

	public PurchaseOrders(DeliveryAdress deliveryAdress, Date purchaseDate) {
		this.deliveryAdress = deliveryAdress;
		this.purchaseDate = purchaseDate;
	}

	public PurchaseOrders(DeliveryAdress deliveryAdress, Date purchaseDate, DeliveryPackages deliveryPackages,
			Billing billing, Set shoppingCarts) {
		this.deliveryAdress = deliveryAdress;
		this.purchaseDate = purchaseDate;
		this.deliveryPackages = deliveryPackages;
		this.billing = billing;
		this.shoppingCarts = shoppingCarts;
	}

	public Integer getIdPurchaseOrder() {
		return this.idPurchaseOrder;
	}

	public void setIdPurchaseOrder(Integer idPurchaseOrder) {
		this.idPurchaseOrder = idPurchaseOrder;
	}

	public DeliveryAdress getDeliveryAdress() {
		return this.deliveryAdress;
	}

	public void setDeliveryAdress(DeliveryAdress deliveryAdress) {
		this.deliveryAdress = deliveryAdress;
	}

	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public DeliveryPackages getDeliveryPackages() {
		return this.deliveryPackages;
	}

	public void setDeliveryPackages(DeliveryPackages deliveryPackages) {
		this.deliveryPackages = deliveryPackages;
	}

	public Billing getBilling() {
		return this.billing;
	}

	public void setBilling(Billing billing) {
		this.billing = billing;
	}

	public Set getShoppingCarts() {
		return this.shoppingCarts;
	}

	public void setShoppingCarts(Set shoppingCarts) {
		this.shoppingCarts = shoppingCarts;
	}

}
