package run;
// Generated Jun 11, 2021, 1:48:56 AM by Hibernate Tools 5.4.30.Final

/**
 * ShoppingCart generated by hbm2java
 */
public class ShoppingCart implements java.io.Serializable {

	private Integer idShoppingCart;
	private Articles articles;
	private PurchaseOrders purchaseOrders;

	public ShoppingCart() {
	}

	public ShoppingCart(Articles articles, PurchaseOrders purchaseOrders) {
		this.articles = articles;
		this.purchaseOrders = purchaseOrders;
	}

	public Integer getIdShoppingCart() {
		return this.idShoppingCart;
	}

	public void setIdShoppingCart(Integer idShoppingCart) {
		this.idShoppingCart = idShoppingCart;
	}

	public Articles getArticles() {
		return this.articles;
	}

	public void setArticles(Articles articles) {
		this.articles = articles;
	}

	public PurchaseOrders getPurchaseOrders() {
		return this.purchaseOrders;
	}

	public void setPurchaseOrders(PurchaseOrders purchaseOrders) {
		this.purchaseOrders = purchaseOrders;
	}

}
