package run;
// Generated Jun 11, 2021, 1:48:56 AM by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * States generated by hbm2java
 */
public class States implements java.io.Serializable {

	private Integer idState;
	private Country country;
	private String state;
	private Set cities = new HashSet(0);
	private Set deliveryAdresses = new HashSet(0);

	public States() {
	}

	public States(Country country, String state) {
		this.country = country;
		this.state = state;
	}

	public States(Country country, String state, Set cities, Set deliveryAdresses) {
		this.country = country;
		this.state = state;
		this.cities = cities;
		this.deliveryAdresses = deliveryAdresses;
	}

	public Integer getIdState() {
		return this.idState;
	}

	public void setIdState(Integer idState) {
		this.idState = idState;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Set getCities() {
		return this.cities;
	}

	public void setCities(Set cities) {
		this.cities = cities;
	}

	public Set getDeliveryAdresses() {
		return this.deliveryAdresses;
	}

	public void setDeliveryAdresses(Set deliveryAdresses) {
		this.deliveryAdresses = deliveryAdresses;
	}

}
